//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int custId { get; set; }
        public string custName { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public System.DateTime fromdate { get; set; }
        public System.DateTime todate { get; set; }
        public decimal totalfare { get; set; }
        public int rating { get; set; }
        public Nullable<int> eId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
