//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public int TaxiID { get; set; }
        public string TaxiNumber { get; set; }
        public string TaxiModel { get; set; }
        public int TaxiOwnerId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
